In [17]:
import numpy as np
new_arry=np.array(([1,2,3],[4,5,6]))
my_list=new_arry.tolist()
print(my_list)
print(new_arry[0,2])

[[1, 2, 3], [4, 5, 6]]
3


In [20]:
import numpy as np
a=np.array(([1,2,3],[7,8,9],[4,5,6]))
print(a)
x=sum(a.diagonal())
print(x)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
15


In [21]:
import numpy as np
a=np.array(([1,2,3],[7,8,9],[4,5,6]))
print(a)
x=np.trace(a)
print(x)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
15


In [48]:
import numpy as np
rand=np.random.randint(0,10,size=(int(input("x= ")),int(input("y= "))))
print(rand)
z=int(input("enter value "))
print("values bigger are",rand[rand>z])

x= 4
y= 3
[[9 3 4]
 [2 8 9]
 [4 7 1]
 [4 1 3]]
enter value 7
values bigger are [9 8 9]


In [52]:
import numpy as np
A=np.array(([2,5,4],[6,4,7]))
B=np.array(([2,9,3],[7,8,5]))
C=A+B
print(C)

[[ 4 14  7]
 [13 12 12]]


In [53]:
import numpy as np
X = np.array(([1,3,5],[4,7,2]))
print(X)
Y = X - X.mean()
print(Y)

[[1 3 5]
 [4 7 2]]
[[-2.66666667 -0.66666667  1.33333333]
 [ 0.33333333  3.33333333 -1.66666667]]
